name: Kubescape 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
   
jobs:
  configuration-validation-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Kubescape
        run: curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash
        
      - name: Scan files
        run: kubescape scan --exceptions .github/assets/kubescape/exceptions.json -t 0 -f junit -o results.xml sources/

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "results.xml"