name: Kubescape 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
   
jobs:
  nsa-security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Kubescape
        run: curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash
        
      - name: Scan YAML files
        run: kubescape scan --exceptions .github/assets/kubescape/exceptions.json -t 0 sources/